# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - smbctestpetclinic

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'microsoft'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/target/spring-petclinic-2.5.0-SNAPSHOT.zip'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
      
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      # NEW DEBUGGING STEP: List contents of the workspace after download
      - name: List downloaded artifact contents
        run: |
          echo "Listing contents of ${{ github.workspace }}/java-app/"
          ls -lR ${{ github.workspace }}/java-app/
          echo "Listing contents of ${{ github.workspace }}/" # Also check root workspace
          ls -lR ${{ github.workspace }}/
          echo "Listing contents of ${{ github.workspace }}/target/" # Check target too, just in case
          ls -lR ${{ github.workspace }}/target/
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'smbctestpetclinic'
          slot-name: 'test3'
          package: '${{ github.workspace }}/java-app/spring-petclinic-2.5.0-SNAPSHOT.zip' 
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C8768A154DE2447281D4B559569DB679 }}
